feature: version extension and python binary

diff --git a/neo4j b/neo4j
--- a/neo4j
+++ b/neo4j
@@ -65,11 +65,6 @@ function _helpers() {
         local app_bin
         app_bin="$app_dir/$NEO4J_APP_BIN"
         chmod +x "$app_bin"
-
-        local java_resources
-        java_resources=$ROOT_DIR/src/main/resources
-        echo "Copying neo4j app binary to java extension resources: $java_resources"
-        cp "$app_bin" "$java_resources"
     }
 
     function _docker_build() {
@@ -143,6 +138,13 @@ function _commands() {
         elif _should_run_project "neo4j_extension"; then
             _print_step "Building the Python app first"
             _build_neo4j_app
+
+            _print_step "Copying neo4j app binary to java extension"
+            local java_resources
+            java_resources=$ROOT_DIR/src/main/resources
+            cp "$app_bin" "$java_resources"
+            echo Copied binary from "$app_bin" to "$java_resources"
+
             _print_step "Compiling the java extension"
             cd "$ROOT_DIR"
             mvn validate package -Dmaven.test.skip=true
@@ -165,26 +167,27 @@ function _commands() {
     function docker_test() {
         if _should_run_project "neo4j_app"; then
             _docker_build base-python
-            _docker_run base-python:latest \
-                ./neo4j setup -p neo4j_app
+            _docker_run base-python:latest ./neo4j setup -p neo4j_app
             _docker_run --mount type=bind,source="$ROOT_DIR"/.data/neo4j,target="$DOCKER_HOME"/.data/neo4j \
                 base-python:latest \
                 ./neo4j test -p neo4j_app
         elif _should_run_project "neo4j_app_format"; then
             _docker_build base-python
-            _docker_run base-python:latest \
-                ./neo4j setup -p neo4j_app
-            _docker_run base-python:latest \
-                ./neo4j format_test_python
+            _docker_run base-python:latest ./neo4j setup -p neo4j_app
+            _docker_run base-python:latest ./neo4j format_test_python
         elif _should_run_project "neo4j_extension"; then
             _docker_build base-java
-            _docker_run base-java:latest \
-                ./neo4j test -p neo4j_extension
+            _docker_run base-java:latest ./neo4j test -p neo4j_extension
         elif _should_run_project "neo4j_extension_format"; then
             _docker_build base-java
             # TODO: mount the target dir to do some maven caching ?
-            _docker_run base-java:latest \
-                ./neo4j format_test_java
+            _docker_run base-java:latest ./neo4j format_test_java
+        elif _should_run_project "neo4j_script"; then
+            _docker_build base-script
+            _docker_run base-script:latest ./neo4j test -p neo4j_script
+        elif _should_run_project "release_version"; then
+            _docker_build base-script
+            _docker_run base-script:latest ./neo4j test -p release_version
         else
             exit_with_message "Can't test project $PROJECT"
         fi
@@ -233,6 +236,10 @@ Please run ./neo4j format"
         curl -sSL https://install.python-poetry.org | python3 -
     )
 
+    function print_version() (
+        cat "$ROOT_DIR"/version
+    )
+
     function run() {
         if [ "$PROJECT" == neo4j_app ]; then
             # TODO: maybe we should run the binary we've copied to the java dir
@@ -240,6 +247,18 @@ Please run ./neo4j format"
         else
             exit_with_message "Can't run project $PROJECT"
         fi
+    }
+
+    function set_version() {
+        # Update root file
+        local file_version
+        file_version=$1
+        if [ -z "$file_version" ]; then exit_with_message "Empty version !"; fi
+        echo "$file_version" > "$ROOT_DIR"/version
+
+        cd "$PYTHON_APP_DIR"
+        _pip_install tomlkit==0.11.6
+        poetry run python "$ROOT_DIR"/scripts/update_versions.py
     }
 
     function setup() {
@@ -301,9 +320,38 @@ Please run ./neo4j format"
         elif _should_run_project "neo4j_extension"; then
             mvn -X test
 
+        elif _should_run_project "neo4j_script"; then
+            for file in "$ROOT_DIR"/scripts/tests/test_*; do
+                "$file"
+            done
+        elif _should_run_project "release_version"; then
+            test_release_version
         else
             exit_with_message "Can't test project $PROJECT"
         fi
+    }
+
+    function test_release_version() {
+        local file_version
+        file_version=$(head -n 1 "$ROOT_DIR"/version)
+
+        # Source version
+        local source_version
+        source_version=$("$ROOT_DIR"/neo4j --version)
+        if ! [ "$source_version" = "$file_version" ]; then exit_with_message "Source version \"$source_version\" differs from \"$file_version\""; fi
+
+        # Java version
+        local java_version
+        java_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        if ! [ "$java_version" = "$file_version" ]; then exit_with_message "Java version \"$java_version\" differs from \"$file_version\""; fi
+
+        # Python version
+        cd "$ROOT_DIR"/neo4j-app || exit
+        local python_version
+        python_version=$(poetry version -s)
+        if ! [ "$python_version" = "$file_version" ]; then exit_with_message "Python version \"$python_version\" differs from \"$file_version\""; fi
+
+        echo "All versions match !"
     }
 }
 
@@ -311,6 +359,7 @@ function _main() {
     PROJECT=
     PROJECTS=
     _ELASTICSEARCH_PORT=
+    PRINT_VERSION=
 
     # Define sub projects here
     PROJECTS=(
@@ -318,6 +367,8 @@ function _main() {
         neo4j_app_format
         neo4j_extension
         neo4j_extension_format
+        neo4j_script
+        release_version
     )
 
     function exit_with_message() {
@@ -357,7 +408,12 @@ function _main() {
                     unset SKIP_NEXT_TYPE_ARG
                 fi
             done
+        elif [[ "$#" == 1 ]]; then
+            if [[ "$1" == "--version" ]]; then
+                PRINT_VERSION=1
+            fi
         fi
+
     }
 
     set -e
@@ -371,14 +427,18 @@ function _main() {
 
     # Export variables
     _export_global_variables
-
-    if [[ $# == 0 ]]; then
-        printf "Error: No command specified\n\n" && exit 1
-    # If we manage to find a command previously declared with _commands, run it
-    elif declare -f "$1" >/dev/null; then
-        "$@"
-    else
-        printf "Error: Invalid command %s\n\n" "$1" && exit 1
+    if [ "${BASH_SOURCE[0]}" -ef "$0" ]
+    then
+        if [[ $# == 0 ]]; then
+            printf "Error: No command specified\n\n" && exit 1
+        # If we manage to find a command previously declared with _commands, run it
+        elif [ -n "$PRINT_VERSION" ]; then
+            print_version
+        elif declare -f "$1" >/dev/null; then
+            "$@"
+        else
+            printf "Error: Invalid command %s\n\n" "$1" && exit 1
+        fi
     fi
 }
 
